### ISSUE TITLE
Not connecting with the flutter app according to the tutorial on medium about dart_meteor

### ISSUE THREAD

**Issue by ioanachi** [tanutapi/simple-meteor-chat#2]
Hi, I tried your tutorial on Medium about connecting a flutter app with a meteor backend but it is not connecting. I keep seeing the button to connect. I don't know what I am doing wrong, I even cloned the repositories to make sure I didn't forget something and I started the meteor app and then the flutter app but no connection is established.

**Comment by tanutapi** [comment]
Hi @ioanachi, are you running your flutter app in the emulator? To access the Meteor localhost:3000 you have to use change the URL to 'http://10.0.2.2:3000'.

Ref: https://stackoverflow.com/questions/5528850/how-do-you-connect-localhost-in-the-android-emulator#:~:text=Use%2010.0.&text=As%20you've%20learned%2C%20when,up%20to%20help%20in%20development.

**Comment by ioanachi** [comment]
It works with the local Ip address, thank you!
